# Generated by Django 5.1.4 on 2025-01-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clothes',
        ),
    ]
